version: '3.7'
services:

  php:
    build:
      context: ./apps/okommerce
      target: symfony_php

    expose:
      - 9000
    depends_on:
      - db
    volumes:
      - ./apps/okommerce:/var/www/html/okommerce

  web:
    image: nginx
    restart: always
    ports:
        - "8080:80"
    depends_on:
        - php
    volumes:
        - ./apps/okommerce:/var/www/html/okommerce
        - ./docker/web/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./docker/web/default.conf:/etc/nginx/sites-enabled/default.conf:ro

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
        discovery.type: "single-node"
    ports:
        - "9200:9200"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8077:8080